### ISSUE TITLE
is supla-scripts still working? or is dead?

### ISSUE THREAD

**Issue by studiowena** [fracz/supla-scripts#40]
I have issue like this and cant run it

`docker/suplascripts.sh start
  ___ _   _ ___ _      _
 / __| | | | _ \ |    /_\
 \__ \ |_| |  _/ |__ / _ \
 |___/\___/|_| |____/_/ \_\
 / __| __ _ _(_)_ __| |_ ___
 \__ \/ _| '_| | '_ \  _(_-<
 |___/\__|_| |_| .__/\__/__/
               |_| by @fracz

Starting SUPLA Scripts containers
Building suplascripts
Step 1/10 : FROM php:7.0.27-apache
 ---> 4dbb41f6ed5b
Step 2/10 : WORKDIR /var/www
 ---> Using cache
 ---> 4c69496f40bc
Step 3/10 : RUN apt-get update     && apt-get install -y --no-install-recommends       libicu-dev       libpq-dev       ca-certificates       ssl-cert       libcurl4-gnutls-dev       git       unzip       mysql-client       supervisor       cron       wget     && update-ca-certificates     && docker-php-ext-install       pdo_mysql       opcache       curl       zip     && apt-get autoremove     && rm -r /var/lib/apt/lists/*
 ---> Running in 29e614bf272e
Get:1 http://security.debian.org jessie/updates InRelease [44.9 kB]
Ign http://deb.debian.org jessie InRelease
Ign http://deb.debian.org jessie-updates InRelease
Get:2 http://deb.debian.org jessie Release.gpg [2420 B]
Ign http://deb.debian.org jessie-updates Release.gpg
Get:3 http://deb.debian.org jessie Release [148 kB]
Ign http://deb.debian.org jessie-updates Release
Err http://deb.debian.org jessie-updates/main armhf Packages

Err http://deb.debian.org jessie-updates/main armhf Packages

Err http://deb.debian.org jessie-updates/main armhf Packages

Err http://deb.debian.org jessie-updates/main armhf Packages

Err http://deb.debian.org jessie-updates/main armhf Packages
  404  Not Found
Get:4 http://security.debian.org jessie/updates/main armhf Packages [794 kB]
Get:5 http://deb.debian.org jessie/main armhf Packages [8898 kB]
Fetched 9888 kB in 1min 19s (124 kB/s)
W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/main/binary-armhf/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
ERROR: Service 'suplascripts' failed to build: The command '/bin/sh -c apt-get update     && apt-get install -y --no-install-recommends       libicu-dev       libpq-dev       ca-certificates       ssl-cert       libcurl4-gnutls-dev       git       unzip       mysql-client       supervisor       cron       wget     && update-ca-certificates     && docker-php-ext-install       pdo_mysql       opcache       curl       zip     && apt-get autoremove     && rm -r /var/lib/apt/lists/*' returned a non-zero code: 100`

**Comment by fracz** [comment]
Jessie backports has been deprecated.

Try swithcing to `stretch` branch for now.

```
git checkout stretch
```

And see if it works.

More info: https://unix.stackexchange.com/questions/508724/failed-to-fetch-jessie-backports-repository

**Comment by studiowena** [comment]
thanks it works, this isssue can be closed as resolved

**Comment by fracz** [comment]
merged to `master`, so if you applied `stretch` branch before, you can go back to "normal" updates with

```
git checkout .
git checkout master
git pull
```
